/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment.gui.harith;

import com.mycompany.assignment.classes.Department;
import com.mycompany.assignment.classes.Doctor;
import com.mycompany.assignment.classes.HospitalReport;
import com.mycompany.assignment.classes.MedicalManager;
import com.mycompany.assignment.classes.doctorShift;
import com.mycompany.assignment.enums.ShiftStatus;
import com.mycompany.assignment.gui.LoginPage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class MedicalManagerPage extends javax.swing.JFrame {

    private MedicalManager MM;
    private ArrayList<Department> departments = Department.getAllDepartments();
    private ArrayList<doctorShift> shifts = doctorShift.getAllShift();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MedicalManagerPage.class.getName());

    /**
     * Creates new form MedicalManagerPage
     *
     * @param MM
     */
    public MedicalManagerPage(MedicalManager MM) throws IOException {
        initComponents();
        this.MM = MM;
        txtFullName.setText(MM.getFullName());
        txtEmail.setText(MM.getEmail());
        txtPassword.setText(MM.getPassword());
        txtPhoneNumber.setText(MM.getPhoneNumber());
        lbWelcomeSubtitle1.setText("Signed in as " + MM.getFullName() + " | Medical Manager");

        DefaultTableModel model = (DefaultTableModel) DeparmentTable.getModel();

        model.setRowCount(0);

        for (Department dept : departments) {
            model.addRow(new Object[]{
                dept.getDepartmentId(),
                dept.getDepartmentName(),
                dept.getSpecialty(),
                dept.getDoctors().length
            });
        }
        DefaultTableModel model2 = (DefaultTableModel) shifttable.getModel();
        
        model2.setRowCount(0);

        for (doctorShift shift : shifts) {
            model2.addRow(new Object[]{
                shift.getshiftId(),
                shift.getdate(),
                shift.getStarttime(),
                shift.getendtime(),
                shift.getDoctor().getFullName(),
                shift.getstatus(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbWelcomeTitle = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lbWelcomeSubtitle = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbWelcomeTitle2 = new javax.swing.JLabel();
        btnLogout1 = new javax.swing.JButton();
        lbWelcomeSubtitle1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeparmentTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        shifttable = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblTotalAppointments = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JLabel();
        lblAverageRating = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(17, 55, 95));

        lbWelcomeTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbWelcomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbWelcomeTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbWelcomeTitle.setText("Hospital Management System");

        btnLogout.setText("LOGOUT");
        btnLogout.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        lbWelcomeSubtitle.setBackground(new java.awt.Color(255, 255, 255));
        lbWelcomeSubtitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbWelcomeSubtitle.setForeground(new java.awt.Color(202, 202, 202));
        lbWelcomeSubtitle.setText("Signed in as NAME | Admin Staff");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonew.png"))); // NOI18N
        jLabel17.setMaximumSize(new java.awt.Dimension(561, 512));
        jLabel17.setPreferredSize(new java.awt.Dimension(561, 512));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbWelcomeTitle)
                    .addComponent(lbWelcomeSubtitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbWelcomeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbWelcomeSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(17, 55, 95));

        lbWelcomeTitle2.setBackground(new java.awt.Color(255, 255, 255));
        lbWelcomeTitle2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbWelcomeTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lbWelcomeTitle2.setText("Hospital Management System");

        btnLogout1.setText("LOGOUT");
        btnLogout1.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnLogout1.addActionListener(this::btnLogout1ActionPerformed);

        lbWelcomeSubtitle1.setBackground(new java.awt.Color(255, 255, 255));
        lbWelcomeSubtitle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbWelcomeSubtitle1.setForeground(new java.awt.Color(202, 202, 202));
        lbWelcomeSubtitle1.setText("Signed in as NAME | Medical Manager");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonew.png"))); // NOI18N
        jLabel19.setMaximumSize(new java.awt.Dimension(561, 512));
        jLabel19.setPreferredSize(new java.awt.Dimension(561, 512));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbWelcomeTitle2)
                    .addComponent(lbWelcomeSubtitle1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout1)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnLogout1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbWelcomeTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbWelcomeSubtitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeparmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Specialty", "Amount of Doctor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DeparmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeparmentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DeparmentTable);
        if (DeparmentTable.getColumnModel().getColumnCount() > 0) {
            DeparmentTable.getColumnModel().getColumn(0).setResizable(false);
            DeparmentTable.getColumnModel().getColumn(1).setResizable(false);
            DeparmentTable.getColumnModel().getColumn(2).setResizable(false);
            DeparmentTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jButton3.setText("Edit Department");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 140, 39));

        jButton4.setText("Add Department");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 122, 39));

        jButton5.setText("Delete Department");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 150, 39));

        jTabbedPane1.addTab("Department Management", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shifttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Shift ID", "Date", "Start Time", "End Time", "Doctor Assigned", "Status"
            }
        ));
        jScrollPane2.setViewportView(shifttable);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 960, 370));

        jButton6.setText("Add New Shift");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 122, 39));

        jButton8.setText("Mark as Cancelled");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 150, 39));

        jButton9.setText("Mark as Completed");
        jButton9.addActionListener(this::jButton9ActionPerformed);
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 390, 150, 39));

        jTabbedPane1.addTab("Shift Roster Management", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Date from :");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 96, -1, -1));

        jLabel3.setText("Date Until :");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 151, -1, -1));

        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 93, 120, -1));

        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 148, 120, -1));

        jButton1.setText("Generate Report Values");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 301, 160, 40));
        jPanel6.add(lblTotalAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 110, -1));
        jPanel6.add(lblTotalRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 120, -1));
        jPanel6.add(lblAverageRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 110, -1));

        jLabel4.setText("Amount of appointments");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel5.setText("Average Rating:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel6.setText("Total Revenue:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jTabbedPane1.addTab("View Report", jPanel6);

        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        jButton2.setText("Submit");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel7.setText("Full Name");

        jLabel8.setText("Email");

        jLabel9.setText("Phone Number");

        jLabel10.setText("Password");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFullName)
                            .addComponent(txtEmail)
                            .addComponent(txtPhoneNumber)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(578, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(46, 46, 46)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update Profile", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
//        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to logout?",
                "Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        MM = null;

        dispose();

        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRow = DeparmentTable.getSelectedRow();

        // check got selected depeatment or not
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a department to edit.",
                    "no selection made",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            Department dept = departments.get(selectedRow);
            String departmentName = JOptionPane.showInputDialog(
                    this,
                    "Department Name:",
                    dept.getDepartmentName()
            );

            if (departmentName == null || departmentName.trim().isEmpty()) {
                return;
            }

            String specialty = JOptionPane.showInputDialog(
                    this,
                    "Specialty:",
                    dept.getSpecialty()
            );

            if (specialty == null || specialty.trim().isEmpty()) {
                return;
            }

            String currentDoctorIds = "";
            for (Doctor doctor : dept.getDoctors()) {
                if (!currentDoctorIds.isEmpty()) {
                    currentDoctorIds += ",";
                }
                currentDoctorIds += doctor.getUserId();
            }

            String input = JOptionPane.showInputDialog(
                    this,
                    "Doctor IDs (comma separated).\nLeave unchanged to keep current doctors.",
                    currentDoctorIds
            );


            dept.updateDetails(departmentName.trim(), specialty.trim());


            if (input != null) {
                Doctor[] doctors;

                if (input.trim().isEmpty()) {
                    doctors = new Doctor[0];
                } else {
                    String[] ids = input.split(",");

                    if (ids.length > 5) {
                        JOptionPane.showMessageDialog(
                                this,
                                "Maximum 5 doctors allowed.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        );
                        return;
                    }

                    doctors = new Doctor[ids.length];

                    for (int i = 0; i < ids.length; i++) {
                        doctors[i] = Doctor.getDoctorById(ids[i].trim());

                        if (doctors[i] == null) {
                            JOptionPane.showMessageDialog(
                                    this,
                                    "doctorid " + ids[i].trim() + " not found.",
                                    "Error",
                                    JOptionPane.ERROR_MESSAGE
                            );
                            return;
                        }
                    }
                }

                dept.updateDoctors(doctors);
            }


            DefaultTableModel model = (DefaultTableModel) DeparmentTable.getModel();
            model.setValueAt(dept.getDepartmentName(), selectedRow, 1);
            model.setValueAt(dept.getSpecialty(), selectedRow, 2);
            model.setValueAt(dept.getDoctors().length, selectedRow, 3);

            JOptionPane.showMessageDialog(
                    this,
                    "department updated successfully."
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {

            String departmentName = JOptionPane.showInputDialog(
                    this,
                    "Enter department name:"
            );

            if (departmentName == null || departmentName.trim().isEmpty()) {
                return;
            }


            String specialty = JOptionPane.showInputDialog(
                    this,
                    "Enter specialty:"
            );

            if (specialty == null || specialty.trim().isEmpty()) {
                return;
            }


            String input = JOptionPane.showInputDialog(
                    this,
                    "Enter doctor IDs separated by commas (max 5).\nExample: 3,5,6\nLeave blank for none."
            );

            Doctor[] doctors;

            if (input == null || input.trim().isEmpty()) {
                doctors = new Doctor[0];
            } else {
                String[] ids = input.split(",");

                if (ids.length > 5) {
                    JOptionPane.showMessageDialog(this, "Maximum 5 doctors allowed.");
                    return;
                }

                doctors = new Doctor[ids.length];

                for (int i = 0; i < ids.length; i++) {
                    doctors[i] = Doctor.getDoctorById(ids[i].trim());

                    if (doctors[i] == null) {
                        JOptionPane.showMessageDialog(
                                this,
                                "Doctor ID " + ids[i].trim() + " does not exist."
                        );
                        return;
                    }
                }
            }

            Department newDepartment = new Department(departmentName, specialty, doctors);

            DefaultTableModel model = (DefaultTableModel) DeparmentTable.getModel();
            model.addRow(new Object[]{
                newDepartment.getDepartmentId(),
                newDepartment.getDepartmentName(),
                newDepartment.getSpecialty(),
                newDepartment.getDoctors().length
            });

            departments.add(newDepartment);

            JOptionPane.showMessageDialog(
                    this,
                    "Department created successfully."
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int selectedRow = DeparmentTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a department to delete.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this department?",
                "Delete Department",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {

            departments.remove(selectedRow);


            DefaultTableModel model = (DefaultTableModel) DeparmentTable.getModel();
            model.removeRow(selectedRow);

            BufferedWriter bw = new BufferedWriter(new FileWriter("Department.txt"));
            bw.close();


            for (Department department : departments) {
                department.saveToFile();
            }

            JOptionPane.showMessageDialog(
                    this,
                    "Department deleted successfully."
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DeparmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeparmentTableMouseClicked

        int row = DeparmentTable.getSelectedRow();
        int col = DeparmentTable.getSelectedColumn();

        if (col == 3 && row >= 0) {
            Department dept = departments.get(row);

            String doctorList = "";

            for (Doctor doctor : dept.getDoctors()) {
                doctorList += doctor.getUserId() + " - " + doctor.getFullName() + "\n";
            }

            if (doctorList.equals("")) {
                doctorList = "No doctors assigned.";
            }

            JOptionPane.showMessageDialog(
                    this,
                    doctorList,
                    dept.getDepartmentName(),
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_DeparmentTableMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            String dateInput = JOptionPane.showInputDialog(
                    this,
                    "Enter shift date (YYYY-MM-DD):"
            );

            if (dateInput == null || dateInput.trim().isEmpty()) {
                return;
            }
            String startInput = JOptionPane.showInputDialog(
                    this,
                    "Enter start time (HH:MM):"
            );

            if (startInput == null || startInput.trim().isEmpty()) {
                return;
            }

            String endInput = JOptionPane.showInputDialog(
                    this,
                    "Enter end time (HH:MM):"
            );

            if (endInput == null || endInput.trim().isEmpty()) {
                return;
            }

            String doctorId = JOptionPane.showInputDialog(
                    this,
                    "Enter doctor ID:"
            );

            if (doctorId == null || doctorId.trim().isEmpty()) {
                return;
            }


            LocalDate shiftDate = LocalDate.parse(dateInput.trim());
            LocalTime startTime = LocalTime.parse(startInput.trim());
            LocalTime endTime = LocalTime.parse(endInput.trim());


            if (!endTime.isAfter(startTime)) {
                JOptionPane.showMessageDialog(
                        this,
                        "End time must be after start time.",
                        "Invalid Time",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }


            Doctor doctor = Doctor.getDoctorById(doctorId.trim());

            if (doctor == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Doctor ID not found.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            doctorShift newShift = new doctorShift(
                    shiftDate,
                    startTime,
                    endTime,
                    doctor
            );


            shifts.add(newShift);


            DefaultTableModel model = (DefaultTableModel) shifttable.getModel();
            model.addRow(new Object[]{
                newShift.getshiftId(),
                newShift.getdate(),
                newShift.getStarttime(),
                newShift.getendtime(),
                doctor.getFullName(), 
                newShift.getstatus()
            });

            JOptionPane.showMessageDialog(
                    this,
                    "Shift created successfully."
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Invalid input.\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int selectedRow = shifttable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a shift to cancel.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Cancel this shift?",
                "Cancel Shift",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            doctorShift shift = shifts.get(selectedRow);

            if (shift.getstatus() == ShiftStatus.CANCELLED) {
                JOptionPane.showMessageDialog(
                        this,
                        "this shift is already cancelled"
                );
                return;
            }

            shift.cancelShift();
            DefaultTableModel model = (DefaultTableModel) shifttable.getModel();
            model.setValueAt(shift.getstatus(), selectedRow, 5);

            JOptionPane.showMessageDialog(
                    this,
                    "shift cancelled successfully"
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int selectedRow = shifttable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a shift to mark as completed.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Mark this shift as completed?",
                "Complete Shift",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            doctorShift shift = shifts.get(selectedRow);

            if (shift.getstatus() == ShiftStatus.COMPLETED) {
                JOptionPane.showMessageDialog(
                        this,
                        "This shift is already completed."
                );
                return;
            }

            shift.markCompleted();

            DefaultTableModel model = (DefaultTableModel) shifttable.getModel();
            model.setValueAt(shift.getstatus(), selectedRow, 5);

            JOptionPane.showMessageDialog(
                    this,
                    "Shift marked as completed successfully."
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LocalDate startDate;
        LocalDate endDate;
        try {
            startDate = LocalDate.parse(jTextField1.getText().trim());
            endDate = LocalDate.parse(jTextField2.getText().trim());

            HospitalReport report = new HospitalReport(startDate, endDate);

            lblTotalAppointments.setText(String.valueOf(report.calculateAppointments()));
            lblTotalRevenue.setText(String.valueOf(report.calculateRevenue()));
            lblAverageRating.setText(String.format("%.2f", report.calculateAverageRating()));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    
                    this,
                    "Please enter dates in YYYY-MM-DD format.",
                    "Invalid Date",
                    JOptionPane.ERROR_MESSAGE
            );
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String fullName = txtFullName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhoneNumber.getText().trim();
        String password = txtPassword.getText().trim();
        String oldpassword = MM.getPassword();

        MM.editProfile(
                txtFullName.getText().trim(),
                txtEmail.getText().trim(),
                txtPhoneNumber.getText().trim()
        );

        boolean success = MM.changePassword(
                oldpassword,
                txtPassword.getText()
        );

        if (success) {
            JOptionPane.showMessageDialog(this, "Profile Updated.");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DeparmentTable;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbWelcomeSubtitle;
    private javax.swing.JLabel lbWelcomeSubtitle1;
    private javax.swing.JLabel lbWelcomeTitle;
    private javax.swing.JLabel lbWelcomeTitle2;
    private javax.swing.JLabel lblAverageRating;
    private javax.swing.JLabel lblTotalAppointments;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JTable shifttable;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
