package com.mycompany.assignment.gui.XuHengPatient;


import com.mycompany.assignment.classes.Patient;
import com.mycompany.assignment.classes.doctorShift;
import com.mycompany.assignment.classes.Appointment;
import java.io.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class BookingConsultationPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingConsultationPage.class.getName());
    private Patient patient;
    private DefaultTableModel model = new DefaultTableModel();
    private String columnName[] = {"Available Date","Start Time","End Time","DoctorID","DoctorName"};
    private DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();
    /**
     * Creates new form BookingConsultationPage
     */
    public BookingConsultationPage(Patient patient) throws IOException {
        initComponents();
        this.patient = patient;
        model.setColumnIdentifiers(columnName);
        List<doctorShift> slots = patient.viewAvailableSlots();
        for (doctorShift slot : slots) {
        model.addRow(new Object[]{
            slot.getShiftDate(),
            slot.getStartTime(),
            slot.getEndTime(),
            slot.getDoctor().getUserId(),
            slot.getDoctor().getFullName()
        });
        }
        
        for (int row = 0; row < jTable1.getRowCount(); row++) {
            String doctorID = jTable1.getValueAt(row, 3).toString();

            boolean exists = false;

            for (int i = 0; i < comboModel.getSize(); i++) {
                if (comboModel.getElementAt(i).equals(doctorID)) {
                    exists = true;
                    break;
                }
            }

            if (!exists) {
                comboModel.addElement(doctorID);
            }
        }

        DoctorIDCMB.setModel(comboModel);
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        RescheduleBTN = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        Booking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DoctorIDCMB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        doctorLBL = new javax.swing.JLabel();
        AppDateTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        STTF = new javax.swing.JTextField();
        ETTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(model);
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        RescheduleBTN.setText(" Reschedule");
        RescheduleBTN.addActionListener(this::RescheduleBTNActionPerformed);

        BackBTN.setBackground(new java.awt.Color(102, 153, 0));
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-button (1).png"))); // NOI18N
        BackBTN.setText("Back");
        BackBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 0), null, null));
        BackBTN.addActionListener(this::BackBTNActionPerformed);

        Booking.setText("Booking");
        Booking.addActionListener(this::BookingActionPerformed);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Doctor Available Slots");

        jLabel2.setText("DoctorID:");

        jLabel3.setText("AppointmentDate:");

        jLabel4.setText("StartTime:");

        jLabel5.setText("EndTime:");

        DoctorIDCMB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorIDCMBMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DoctorIDCMBMouseReleased(evt);
            }
        });
        DoctorIDCMB.addActionListener(this::DoctorIDCMBActionPerformed);

        jLabel6.setText("DoctorName: ");

        doctorLBL.setText("______");

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("YYYY-MM-DD e.g. 2026-10-20");

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("HH:MM e.g. 05:30");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DoctorIDCMB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(doctorLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(STTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AppDateTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ETTF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))))
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RescheduleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BackBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DoctorIDCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(doctorLBL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(AppDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(STTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(ETTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Booking)
                        .addGap(25, 25, 25)
                        .addComponent(RescheduleBTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RescheduleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RescheduleBTNActionPerformed
        ReschedulingPage page = null;
        try {
            page = new ReschedulingPage(patient); 
            page.setVisible(true);
            dispose();
        } catch (IOException ex) {
            System.getLogger(BookingConsultationPage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(null,"System error. Please try again.");
        }
        
    }//GEN-LAST:event_RescheduleBTNActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        PatientMenuPage page= new PatientMenuPage(patient);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingActionPerformed
        LocalDate AD =null;
        LocalTime ST = null;
        LocalTime ET = null;
        try{
            AD = LocalDate.parse(AppDateTF.getText());
        }catch(DateTimeParseException ex){
            JOptionPane.showMessageDialog(null, "Please follow LocalDate Format YYYY-MM-DD, eg. 2026-01-31");
            return;
        }
        try{
            ST = LocalTime.parse(STTF.getText());
            ET = LocalTime.parse(ETTF.getText());
        }catch(DateTimeParseException ex){
            JOptionPane.showMessageDialog(null, "Please follow LocalTime Format HH:MM(24 hours format), eg. 09:30");
            return;
        }
        
        try {
            Appointment APT = new Appointment(
                    patient.getUserId(),
                    DoctorIDCMB.getSelectedItem().toString(),
                    AD,
                    ST,
                    ET);
            
            patient.bookAppointment(APT);
            JOptionPane.showMessageDialog(null, "Appointment Booked.");
            AppDateTF.setText("");
            STTF.setText("");
            ETTF.setText("");
        } catch (IOException ex) {
            System.getLogger(BookingConsultationPage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(null, "System error. Please try again.");
        }catch(IllegalArgumentException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "System error. Please try again.");
        }
    }//GEN-LAST:event_BookingActionPerformed

    private void DoctorIDCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorIDCMBActionPerformed

    }//GEN-LAST:event_DoctorIDCMBActionPerformed

    private void DoctorIDCMBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorIDCMBMouseReleased
            String doctorID = DoctorIDCMB.getSelectedItem().toString();
            try{
            FileReader fr = new FileReader("accountlist.txt");
            BufferedReader br = new BufferedReader(fr);

            String line = null;
                while((line = br.readLine()) !=null){
                String value[] = line.split(",");
                if(value[0].equals(doctorID)){
                    doctorLBL.setText(value[1]);
                }
        }
                br.close();
                fr.close();}
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                }
    }//GEN-LAST:event_DoctorIDCMBMouseReleased

    private void DoctorIDCMBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorIDCMBMouseClicked

    }//GEN-LAST:event_DoctorIDCMBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingConsultationPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AppDateTF;
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton Booking;
    private javax.swing.JComboBox<String> DoctorIDCMB;
    private javax.swing.JTextField ETTF;
    private javax.swing.JButton RescheduleBTN;
    private javax.swing.JTextField STTF;
    private javax.swing.JLabel doctorLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private BookingConsultationPage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
