package com.mycompany.assignment.gui.XuHengPatient;


import com.mycompany.assignment.classes.Patient;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class EditFeedbackPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditFeedbackPage.class.getName());
    private Patient patient;
    private DefaultTableModel model = new DefaultTableModel();
    private String columnName[] = {"FeedbackID","DoctorID","Doctor Name","Rating","Comment","Date"};
    /**
     * Creates new form EditFeedbackPage
     */
    public EditFeedbackPage(Patient patient) throws FileNotFoundException, IOException {
        initComponents();
        this.patient = patient;
        model.setColumnIdentifiers(columnName);
        FileReader fr = new FileReader("Feedback.txt");
        BufferedReader br = new BufferedReader(fr);
        ArrayList<String[]> Feedbacks =new ArrayList<>();
        String line;
        while ((line=br.readLine())!=null){
            Feedbacks.add(line.split(";"));
        }
        int i = 0;
        while(i<Feedbacks.size()){
            if((Feedbacks.get(i)[1]).equals(patient.getUserId())){
                
                String line2;
                String doctorName = null;
                FileReader fr2 = new FileReader("accountlist.txt");
                BufferedReader br2 = new BufferedReader(fr2);
                while ((line2 = br2.readLine()) != null) {
                        String value2[] = line2.split(",");
                        if(value2[0].equals(Feedbacks.get(i)[2])){
                            doctorName = value2[1];
                            break;
                        }
                    } 
                    br2.close();
                    fr2.close();
                        
                Object[] row ={
                    Feedbacks.get(i)[0],
                    Feedbacks.get(i)[2],
                    doctorName,
                    Feedbacks.get(i)[3],
                    Feedbacks.get(i)[4],
                    Feedbacks.get(i)[5]
                };
                model.addRow(row);
                i++;
            }else{
                i++;
            }
        }
        br.close();
        fr.close();
    }

    private EditFeedbackPage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackBTN = new javax.swing.JButton();
        SubmitBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CommentTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BackBTN.setBackground(new java.awt.Color(102, 204, 0));
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-button (1).png"))); // NOI18N
        BackBTN.setText("Back");
        BackBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 255, 0), null, null));
        BackBTN.addActionListener(this::BackBTNActionPerformed);

        SubmitBTN.setText("Submit");
        SubmitBTN.addActionListener(this::SubmitBTNActionPerformed);

        jLabel1.setText("Past Comment");

        CommentTA.setColumns(20);
        CommentTA.setRows(5);
        jScrollPane2.setViewportView(CommentTA);

        jLabel2.setText("New Comment:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(BackBTN)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        FeedbackPage page = null;
        try {
            page = new FeedbackPage(patient);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "System error. Please try again.");
            System.getLogger(EditFeedbackPage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int row = jTable1.getSelectedRow();
        
        String Comment = String.valueOf(model.getValueAt(row, 4));
        CommentTA.setText(Comment);
    }//GEN-LAST:event_jTable1MouseReleased

    private void SubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTNActionPerformed
        int row = jTable1.getSelectedRow();
        if (CommentTA.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please provide comment.");
        }else if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select a feedback to change.");
        }
        else{
        String FeedbackID = String.valueOf(model.getValueAt(row, 0));
        patient.editFeedback(FeedbackID, CommentTA.getText());
        JOptionPane.showMessageDialog(null, "Comment Edited.");
        try {
            EditFeedbackPage page = new EditFeedbackPage(patient);
            page.setVisible(true);
            dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "System error. Please try again.");
            System.getLogger(EditFeedbackPage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }}
        
    }//GEN-LAST:event_SubmitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditFeedbackPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JTextArea CommentTA;
    private javax.swing.JButton SubmitBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
