package com.mycompany.assignment.gui.XuHengPatient;


import com.mycompany.assignment.classes.Patient;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class FeedbackPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FeedbackPage.class.getName());
    private Patient patient;
    private int Rating = 0;
    private String Comment;
    private DefaultTableModel model = new DefaultTableModel();
    private String columnName[] = {"DoctorID","Name"};
    /**
     * Creates new form FeedbackPage
     */
    public FeedbackPage(Patient patient) throws FileNotFoundException, IOException {
        initComponents();
        this.patient = patient;
        model.setColumnIdentifiers(columnName);
        try(FileReader fr = new FileReader("AppointmentSchedule.txt");
            BufferedReader br = new BufferedReader(fr);){
           
            String line;
            
            while ((line = br.readLine()) != null) {
                String value[] = line.split(",");
                String doctorID = value[2];
                String doctorName = null;
                
                if(value[1].equals(patient.getUserId()) && value[6].equals("COMPLETE")){
                    String line2;
                    doctorID = value[2];
                    
                     
                    FileReader fr1 = new FileReader("accountlist.txt");
                    BufferedReader br1 = new BufferedReader(fr1);
                    
                    while ((line2 = br1.readLine()) != null) {
                        String value2[] = line2.split(",");
                        if(value2[0].equals(doctorID)){
                            doctorName = value2[1];
                            break;
                        }
                    } 
                    br1.close();
                    fr1.close();
                }
                
                boolean exists = false;
                
                for (int row = 0; row < model.getRowCount(); row++) { //getRowCount to know how many row at current
                    if (model.getValueAt(row, 0).toString().equals(doctorID)) {
                        exists = true;
                        break;
                    }
                }
                
                if (!exists && doctorName !=null) {
                    model.addRow(new Object[]{
                        doctorID,
                        doctorName
                    });
                }
            }   
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "System Error. Please try again.");
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }

    private FeedbackPage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentTA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        FIVESRB = new javax.swing.JRadioButton();
        FOURSRB = new javax.swing.JRadioButton();
        THREESRB = new javax.swing.JRadioButton();
        TWOSRB = new javax.swing.JRadioButton();
        ONESRB = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        BackBTN = new javax.swing.JButton();
        EditBTN = new javax.swing.JButton();
        SubmitBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MainICON = new javax.swing.JLabel();

        jLabel3.setText("Rating:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CommentTA.setColumns(20);
        CommentTA.setRows(5);
        jScrollPane1.setViewportView(CommentTA);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Feedback");

        buttonGroup1.add(FIVESRB);
        FIVESRB.setText("5 Stars");
        FIVESRB.addActionListener(this::FIVESRBActionPerformed);

        buttonGroup1.add(FOURSRB);
        FOURSRB.setText("4 Stars");
        FOURSRB.addActionListener(this::FOURSRBActionPerformed);

        buttonGroup1.add(THREESRB);
        THREESRB.setText("3 Stars");
        THREESRB.addActionListener(this::THREESRBActionPerformed);

        buttonGroup1.add(TWOSRB);
        TWOSRB.setText("2 Stars");
        TWOSRB.addActionListener(this::TWOSRBActionPerformed);

        buttonGroup1.add(ONESRB);
        ONESRB.setText("1 Star");
        ONESRB.addActionListener(this::ONESRBActionPerformed);

        jLabel2.setText("Comment:");

        BackBTN.setBackground(new java.awt.Color(102, 153, 0));
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-button (1).png"))); // NOI18N
        BackBTN.setText("Back");
        BackBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 255, 0), null, null));
        BackBTN.addActionListener(this::BackBTNActionPerformed);

        EditBTN.setText("Edit Past Comment");
        EditBTN.addActionListener(this::EditBTNActionPerformed);

        SubmitBTN.setText("Submit Feedback");
        SubmitBTN.addActionListener(this::SubmitBTNActionPerformed);

        jLabel4.setText("Rating:");

        jTable1.setModel(model);
        jScrollPane2.setViewportView(jTable1);

        MainICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonew.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainICON, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SubmitBTN)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FIVESRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FOURSRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(THREESRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TWOSRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ONESRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)))
                        .addGap(87, 87, 87))))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(EditBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainICON)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(BackBTN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIVESRB)
                    .addComponent(FOURSRB)
                    .addComponent(THREESRB)
                    .addComponent(TWOSRB)
                    .addComponent(ONESRB))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditBTN)
                    .addComponent(SubmitBTN))
                .addGap(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        PatientMenuPage page = null;
        page = new PatientMenuPage(patient);
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void EditBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBTNActionPerformed
        EditFeedbackPage page = null;
        try {
            page = new EditFeedbackPage(patient);
        } catch (IOException ex) {
            System.getLogger(FeedbackPage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditBTNActionPerformed

    private void SubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTNActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please select a doctor.");
        }
        else if(Rating == 0 || CommentTA.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please provide rating and service.");
        }else{
            try {
                patient.submitFeedback(Rating, CommentTA.getText(),String.valueOf(model.getValueAt(row, 0)));
            } catch (IOException ex) {
                System.getLogger("Feedback Submit Failed.");
            }
            JOptionPane.showMessageDialog(null, "Feedback Submitted.");
            CommentTA.setText("");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_SubmitBTNActionPerformed

    private void FIVESRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIVESRBActionPerformed
        // TODO add your handling code here:
        Rating = 5;
    }//GEN-LAST:event_FIVESRBActionPerformed

    private void FOURSRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOURSRBActionPerformed
        // TODO add your handling code here:
        Rating = 4;
    }//GEN-LAST:event_FOURSRBActionPerformed

    private void THREESRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THREESRBActionPerformed
        // TODO add your handling code here:
        Rating = 3;
    }//GEN-LAST:event_THREESRBActionPerformed

    private void TWOSRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWOSRBActionPerformed
        // TODO add your handling code here:
        Rating = 2;
    }//GEN-LAST:event_TWOSRBActionPerformed

    private void ONESRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONESRBActionPerformed
        // TODO add your handling code here:
        Rating = 1;
    }//GEN-LAST:event_ONESRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FeedbackPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JTextArea CommentTA;
    private javax.swing.JButton EditBTN;
    private javax.swing.JRadioButton FIVESRB;
    private javax.swing.JRadioButton FOURSRB;
    private javax.swing.JLabel MainICON;
    private javax.swing.JRadioButton ONESRB;
    private javax.swing.JButton SubmitBTN;
    private javax.swing.JRadioButton THREESRB;
    private javax.swing.JRadioButton TWOSRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
