package com.mycompany.assignment.gui.XuHengPatient;


import com.mycompany.assignment.classes.Patient;
import com.mycompany.assignment.gui.LoginPage;
import java.io.FileNotFoundException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
import java.io.*;
import javax.swing.JOptionPane;
public class PatientMenuPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PatientMenuPage.class.getName());
    private Patient patient;
    /**
     * Creates new form PatientMenu
     */
    public PatientMenuPage(Patient patient){
        initComponents();
        this.patient = patient;
        PatientNameLbl.setText(patient.getFullName());
//        PatientNameLbl.setHorizontalTextPosition();
    }

    private PatientMenuPage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookingBTN = new javax.swing.JButton();
        EditProfileBTN = new javax.swing.JButton();
        PMHBTN = new javax.swing.JButton();
        PPBTN = new javax.swing.JButton();
        FeedbackBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PatientNameLbl = new javax.swing.JLabel();
        LogOutBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PatientPhotoLBL = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        MainICON = new javax.swing.JLabel();
        BookingPNG = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Main Page");
        setFocusable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        BookingBTN.setBackground(new java.awt.Color(51, 102, 255));
        BookingBTN.setForeground(new java.awt.Color(255, 255, 255));
        BookingBTN.setText("Booking");
        BookingBTN.addActionListener(this::BookingBTNActionPerformed);

        EditProfileBTN.setBackground(new java.awt.Color(102, 0, 153));
        EditProfileBTN.setForeground(new java.awt.Color(255, 255, 255));
        EditProfileBTN.setText("Edit Profile");
        EditProfileBTN.addActionListener(this::EditProfileBTNActionPerformed);

        PMHBTN.setBackground(new java.awt.Color(0, 204, 204));
        PMHBTN.setForeground(new java.awt.Color(255, 255, 255));
        PMHBTN.setText("Personal Medical History");
        PMHBTN.addActionListener(this::PMHBTNActionPerformed);

        PPBTN.setBackground(new java.awt.Color(51, 153, 0));
        PPBTN.setForeground(new java.awt.Color(255, 255, 255));
        PPBTN.setText("Personal Perscription");
        PPBTN.addActionListener(this::PPBTNActionPerformed);

        FeedbackBTN.setBackground(new java.awt.Color(255, 153, 0));
        FeedbackBTN.setForeground(new java.awt.Color(255, 255, 255));
        FeedbackBTN.setText("Feedback");
        FeedbackBTN.addActionListener(this::FeedbackBTNActionPerformed);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Hospital System");

        PatientNameLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        PatientNameLbl.setText("Patient Name");
        PatientNameLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PatientNameLbl.setFocusable(false);
        PatientNameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LogOutBTN.setBackground(new java.awt.Color(204, 204, 204));
        LogOutBTN.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LogOutBTN.setForeground(new java.awt.Color(255, 51, 51));
        LogOutBTN.setText("Log Out");
        LogOutBTN.addActionListener(this::LogOutBTNActionPerformed);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        PatientPhotoLBL.setIcon(new javax.swing.ImageIcon("C:\\JAVA sama\\Y2S1-OODJ-assignment-main\\src\\main\\java\\images\\patient.jpg")); // NOI18N

        MainICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonew.png"))); // NOI18N

        jDesktopPane1.setLayer(MainICON, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainICON, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainICON)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(PatientPhotoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientPhotoLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
        );

        BookingPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking (2).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical-checkup (1) (1).png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prescription (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback (1).png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogOutBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(PatientNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BookingPNG, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PPBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PMHBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BookingBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FeedbackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogOutBTN)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PatientNameLbl)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookingPNG, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PMHBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PPBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FeedbackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EditProfileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileBTNActionPerformed
        // TODO add your handling code here:
        EditProfilePage page = null;
        page = new EditProfilePage(patient);
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditProfileBTNActionPerformed

    private void LogOutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBTNActionPerformed
        // TODO add your handling code here:
        int Confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?","Log Out",JOptionPane.YES_NO_OPTION);
        if(Confirm == JOptionPane.YES_OPTION){
        LoginPage page = new LoginPage();
        page.setVisible(true);
        this.dispose();}
    }//GEN-LAST:event_LogOutBTNActionPerformed

    private void BookingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingBTNActionPerformed
        BookingConsultationPage page=null;
        try {
            page = new BookingConsultationPage(patient);
        } catch (IOException ex) {
            System.getLogger(PatientMenuPage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(null, "System Error. Please Try Again.");
        }
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_BookingBTNActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here
    }//GEN-LAST:event_formWindowDeactivated

    private void PPBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPBTNActionPerformed
        // TODO add your handling code here:
        PatientPrescriptionPage page = null;
        try {
            page = new PatientPrescriptionPage(patient);
        } catch (IOException ex) {
            System.getLogger(PatientMenuPage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(null, "System Error. Please Try Again.");
        }
        page.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_PPBTNActionPerformed

    private void PMHBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMHBTNActionPerformed
        PatientMedicalRecord page = null;
        try {
            page = new PatientMedicalRecord(patient);
        } catch (IOException ex) {
            System.getLogger(PatientMenuPage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(null, "System Error. Please Try Again.");
        }
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PMHBTNActionPerformed

    private void FeedbackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackBTNActionPerformed
        FeedbackPage page = null;
        try {
            page = new FeedbackPage(patient);
        } catch (IOException ex) {
            System.getLogger(PatientMenuPage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(null, "System Error. Please Try Again.");
        }
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FeedbackBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PatientMenuPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookingBTN;
    private javax.swing.JLabel BookingPNG;
    private javax.swing.JButton EditProfileBTN;
    private javax.swing.JButton FeedbackBTN;
    private javax.swing.JButton LogOutBTN;
    private javax.swing.JLabel MainICON;
    private javax.swing.JButton PMHBTN;
    private javax.swing.JButton PPBTN;
    private javax.swing.JLabel PatientNameLbl;
    private javax.swing.JLabel PatientPhotoLBL;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
