/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment.gui.XuHengPatient;

import com.mycompany.assignment.classes.Appointment;
import com.mycompany.assignment.classes.Patient;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ReschedulingPage extends javax.swing.JFrame {
    private Patient patient;
    private DefaultTableModel model = new DefaultTableModel();
    private String columnName[] = {"AppointmentID","DoctorID","AppointmentDate","Start Time","End Time","Status"};
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReschedulingPage.class.getName());

    /**
     * Creates new form EditConsultationPage
     */
    public ReschedulingPage(Patient patient) throws IOException {
        initComponents();
        this.patient = patient;
        model.setColumnIdentifiers(columnName);
        FileReader fr = new FileReader("AppointmentSchedule.txt");
        BufferedReader br = new BufferedReader(fr);

        String line = null;
        while((line = br.readLine()) !=null){
            String value[] = line.split(",");
            if(value[1].equals(patient.getUserId())&& value[6].equals("BOOKED")){
            String[] display = {
                value[0],
                value[2],
                value[3],
                value[4],
                value[5],
                value[6]};
            model.addRow(display);
        }
        
        
    }br.close();
        fr.close();
    }

    private ReschedulingPage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RescheduleBTN = new javax.swing.JButton();
        CancelBTN = new javax.swing.JButton();
        STTF = new javax.swing.JTextField();
        doctorNameLBL = new javax.swing.JLabel();
        ETTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AppDateTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doctorIDLBL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BackBTN.setBackground(new java.awt.Color(51, 153, 0));
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-button (1).png"))); // NOI18N
        BackBTN.setText("Back");
        BackBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 255, 0), null, null));
        BackBTN.addActionListener(this::BackBTNActionPerformed);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Consulation ");

        RescheduleBTN.setText("Reschedule");
        RescheduleBTN.addActionListener(this::RescheduleBTNActionPerformed);

        CancelBTN.setText("Cancel Booking");
        CancelBTN.addActionListener(this::CancelBTNActionPerformed);

        doctorNameLBL.setText("______");

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("e.g. 15:30");

        jLabel2.setText("DoctorID:");

        jLabel3.setText("AppointmentDate:");

        jLabel4.setText("StartTime:");

        jLabel5.setText("EndTime:");

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("e.g. 2026-10-20");

        jLabel6.setText("DoctorName: ");

        doctorIDLBL.setText("______");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonew.png"))); // NOI18N
        jLabel9.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(STTF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AppDateTF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ETTF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(doctorNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(doctorIDLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CancelBTN)
                                    .addComponent(RescheduleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(doctorIDLBL))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(doctorNameLBL))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(156, 156, 156)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AppDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(STTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(ETTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RescheduleBTN)
                .addGap(18, 18, 18)
                .addComponent(CancelBTN)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(BackBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        BookingConsultationPage page = null;
        try {
            page = new BookingConsultationPage(patient);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "System Error. Please Try Again.");
        }
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void RescheduleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RescheduleBTNActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a schedule to reschedule.");
            return;
        }
        String APPID = String.valueOf(model.getValueAt(row, 0));
        String doctorID = String.valueOf(model.getValueAt(row,1));
        LocalDate AD = null;
        LocalTime ST = null;
        LocalTime ET = null;
        try{
            AD = LocalDate.parse(AppDateTF.getText());
        }catch(DateTimeParseException ex){
            JOptionPane.showMessageDialog(null, "Please follow LocalDate Format YYYY-MM-DD, eg. 2026-01-31");
            return;
        }
        
        try{
            ST = LocalTime.parse(STTF.getText());
            ET = LocalTime.parse(ETTF.getText());
        }catch(DateTimeParseException ex){
            JOptionPane.showMessageDialog(null, "Please follow LocalTime Format HH:MM(24 hours format), eg. 09:30");
            return;
        }
        
        try {
            Appointment AP = new Appointment(
                    APPID,
                    patient.getUserId(),
                    doctorID,
                    AD,
                    ST,
                    ET
            );
            patient.rescheduleAppointment(AP, 
                    AD,
                    ST,
                    ET);
            
            JOptionPane.showMessageDialog(null, "Schedule updated.");
            ReschedulingPage page = new ReschedulingPage(patient);
            page.setVisible(true);
            dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "System Error. Please Try Again.");
        }
    }//GEN-LAST:event_RescheduleBTNActionPerformed

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        int row = jTable1.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a schedule to cancel.");
            return;
        }
        String APPID = String.valueOf(model.getValueAt(row, 0));
        String doctorID = String.valueOf(model.getValueAt(row,1));
        String APPDate = String.valueOf(model.getValueAt(row, 2));
        String ST = String.valueOf(model.getValueAt(row, 3));
        String ET = String.valueOf(model.getValueAt(row, 4));
        try {
            Appointment AP = new Appointment(
                    APPID,
                    patient.getUserId(),
                    doctorID,
                    LocalDate.parse(APPDate),
                    LocalTime.parse(ST),
                    LocalTime.parse(ET));
            patient.cancelAppointment(AP);
            JOptionPane.showMessageDialog(null, "Schedule Cancelled.");
            ReschedulingPage page = new ReschedulingPage(patient);
            page.setVisible(true);
            dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "System Error. Please Try Again.");
        }
    }//GEN-LAST:event_CancelBTNActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int row = jTable1.getSelectedRow();
        String doctorID = String.valueOf(model.getValueAt(row,1));
        String doctorName = null;
        try{
        FileReader fr = new FileReader("accountlist.txt");
        BufferedReader br = new BufferedReader(fr);

        String line = null;
        while((line = br.readLine()) !=null){
            String value[] = line.split(",");
            if(value[0].equals(doctorID)){
                doctorName = value[1];
        }
        
        
        String APPDate = String.valueOf(model.getValueAt(row, 2));
        String ST = String.valueOf(model.getValueAt(row, 3));
        String ET = String.valueOf(model.getValueAt(row, 4));
        
        doctorIDLBL.setText(doctorID);
        doctorNameLBL.setText(doctorName);
        AppDateTF.setText(APPDate);
        STTF.setText(ST);
        ETTF.setText(ET);
        }br.close();
        fr.close();}catch(Exception e){
                JOptionPane.showMessageDialog(null, "System Error.");
                }
    }//GEN-LAST:event_jTable1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReschedulingPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AppDateTF;
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton CancelBTN;
    private javax.swing.JTextField ETTF;
    private javax.swing.JButton RescheduleBTN;
    private javax.swing.JTextField STTF;
    private javax.swing.JLabel doctorIDLBL;
    private javax.swing.JLabel doctorNameLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
