/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment.gui;

import com.mycompany.assignment.classes.AdminStaff;
import com.mycompany.assignment.classes.Doctor;
import com.mycompany.assignment.classes.MedicalManager;
import com.mycompany.assignment.classes.Patient;
import com.mycompany.assignment.classes.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arifi
 */
public class AdminPage extends javax.swing.JFrame {

    private AdminStaff adminStaff;
    private String editingUserId = null;

    /**
     * Creates new form AdminPage
     *
     * @param adminStaff
     */
    public AdminPage(AdminStaff adminStaff) {
        initComponents();

        this.adminStaff = adminStaff;

        initialCreateUserDialog();

        jLabel1.setText("Admin staff - " + adminStaff.getFullName());

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"User ID", "Full Name", "Email", "Phone Number", "Role", "Active"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        loadUsers();
    }

    private void loadUsers() {
        DefaultTableModel model = (DefaultTableModel) tbUsers.getModel();

        model.setRowCount(0);

        ArrayList<User> users = adminStaff.getUsers();

        for (User user : users) {
            model.addRow(new Object[]{
                user.getUserId(),
                user.getFullName(),
                user.getEmail(),
                user.getPhoneNumber(),
                user.getRole(),
                user.isActive()
            });
        }
    }

    private void initialCreateUserDialog() {
        editingUserId = null;

        cbRole.removeAllItems();
        cbRole.addItem("ADMIN");
        cbRole.addItem("MEDICAL_MANAGER");
        cbRole.addItem("DOCTOR");
        cbRole.addItem("PATIENT");

        txtFullName.setText("");
        txtEmail.setText("");
        txtPhoneNumber.setText("");
        txtPassword.setText("");

        cbRole.setSelectedIndex(0);
        cbActive.setSelected(true);

        btnCreateUser.setText("Create");
        CreateUserDialog.setTitle("Create User");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateUserDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        txtFullName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cbRole = new javax.swing.JComboBox<>();
        cbActive = new javax.swing.JCheckBox();
        btnCreateUser = new javax.swing.JButton();
        btnCancelCreateUser = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnRefreshUsers = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbActive.setText("active");

        btnCreateUser.setText("Create");
        btnCreateUser.addActionListener(this::btnCreateUserActionPerformed);

        btnCancelCreateUser.setText("Cancel");
        btnCancelCreateUser.addActionListener(this::btnCancelCreateUserActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnCreateUser)
                            .addGap(39, 39, 39)
                            .addComponent(btnCancelCreateUser))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(cbActive)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFullName)
                        .addComponent(txtEmail)
                        .addComponent(txtPhoneNumber)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbActive)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateUser)
                    .addComponent(btnCancelCreateUser))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CreateUserDialogLayout = new javax.swing.GroupLayout(CreateUserDialog.getContentPane());
        CreateUserDialog.getContentPane().setLayout(CreateUserDialogLayout);
        CreateUserDialogLayout.setHorizontalGroup(
            CreateUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CreateUserDialogLayout.setVerticalGroup(
            CreateUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnRefreshUsers.setText("Refresh");
        btnRefreshUsers.addActionListener(this::btnRefreshUsersActionPerformed);

        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(this::btnDeleteUserActionPerformed);

        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(this::btnAddUserActionPerformed);

        btnEditUser.setText("Edit User");
        btnEditUser.addActionListener(this::btnEditUserActionPerformed);

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsers.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbUsers);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(btnAddUser)
                .addGap(18, 18, 18)
                .addComponent(btnEditUser)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteUser)
                .addGap(18, 18, 18)
                .addComponent(btnRefreshUsers)
                .addGap(224, 224, 224))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser)
                    .addComponent(btnEditUser)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnRefreshUsers))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Users", jPanel2);

        jLabel1.setText("Admin staff - USER NAME");

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshUsersActionPerformed
        loadUsers();
    }//GEN-LAST:event_btnRefreshUsersActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        initialCreateUserDialog();

        CreateUserDialog.pack();
        CreateUserDialog.setLocationRelativeTo(this);
        CreateUserDialog.setVisible(true);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        String fullName = txtFullName.getText().trim();
        String email = txtEmail.getText().trim();
        String phoneNumber = txtPhoneNumber.getText().trim();
        String password = new String(txtPassword.getPassword());
        String role = cbRole.getSelectedItem().toString();
        boolean active = cbActive.isSelected();

        if (fullName.isEmpty() || email.isEmpty() || phoneNumber.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(CreateUserDialog, "Please fill in all fields.");
            return;
        }

        User user = null;

//        CREATE
        if (editingUserId == null) {
            switch (role) {
                case "ADMIN":
                    user = new AdminStaff(
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "MEDICAL_MANAGER":
                    user = new MedicalManager(
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "DOCTOR":
                    user = new Doctor(
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "PATIENT":
                    user = new Patient(
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;
            }

            if (user != null) {
                boolean success = adminStaff.createUser(user);
                if (success) {
                    JOptionPane.showMessageDialog(CreateUserDialog, "User created successfully.");
                    CreateUserDialog.dispose();

                    loadUsers();
                } else {
                    JOptionPane.showMessageDialog(CreateUserDialog, "Failed to create user.");
                }
            }
        } else {
//            EDIT
            switch (role) {
                case "ADMIN":
                    user = new AdminStaff(
                            editingUserId,
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "MEDICAL_MANAGER":
                    user = new MedicalManager(
                            editingUserId,
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "DOCTOR":
                    user = new Doctor(
                            editingUserId,
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "PATIENT":
                    user = new Patient(
                            editingUserId,
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;
            }

            if (user != null) {
                boolean success = adminStaff.updateUser(user);

                if (success) {
                    JOptionPane.showMessageDialog(CreateUserDialog, "User updated successfully.");

                    CreateUserDialog.dispose();

                    editingUserId = null;

                    loadUsers();
                } else {
                    JOptionPane.showMessageDialog(CreateUserDialog, "Failed to update user.");
                }
            }
        }
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnCancelCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelCreateUserActionPerformed
        CreateUserDialog.dispose();
    }//GEN-LAST:event_btnCancelCreateUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        int selectedRow = tbUsers.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to delete.");
            return;
        }

        String userId = tbUsers.getValueAt(selectedRow, 0).toString();
        String fullName = tbUsers.getValueAt(selectedRow, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete "
                + fullName
                + " (" + userId + ")?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        boolean success = adminStaff.deleteUser(userId);

        if (success) {
            JOptionPane.showMessageDialog(this, "User deleted successfully.");
            loadUsers();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete user.", "Delete Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        int selectedRow = tbUsers.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to edit.");
            return;
        }

        String userId = tbUsers.getValueAt(selectedRow, 0).toString();

        User user = adminStaff.getUser(userId);

        if (user == null) {
            JOptionPane.showMessageDialog(this, "User could not be found.");
            return;
        }

//        Select user want to edit
        editingUserId = userId;

        txtFullName.setText(user.getFullName());
        txtEmail.setText(user.getEmail());
        txtPhoneNumber.setText(user.getPhoneNumber());
        txtPassword.setText(user.getPassword());
        cbRole.setSelectedItem(user.getRole().toString());
        cbActive.setSelected(user.isActive());

        btnCreateUser.setText("Save Changes");
        CreateUserDialog.setTitle("Edit User");

        CreateUserDialog.pack();
        CreateUserDialog.setLocationRelativeTo(this);
        CreateUserDialog.setVisible(true);
    }//GEN-LAST:event_btnEditUserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CreateUserDialog;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCancelCreateUser;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefreshUsers;
    private javax.swing.JCheckBox cbActive;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbUsers;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
