/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment.gui;

import com.mycompany.assignment.classes.AdminStaff;
import com.mycompany.assignment.classes.Doctor;
import com.mycompany.assignment.classes.InsuranceNetwork;
import com.mycompany.assignment.classes.MedicalManager;
import com.mycompany.assignment.classes.Patient;
import com.mycompany.assignment.classes.User;
import com.mycompany.assignment.loginchangelater;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arifi
 */
public class AdminPage extends javax.swing.JFrame {

    private AdminStaff adminStaff;
    private String editingUserId = null;
    private String editingInsuranceId = null;

    /**
     * Creates new form AdminPage
     *
     * @param adminStaff
     */
    public AdminPage(AdminStaff adminStaff) {
        initComponents();

        this.adminStaff = adminStaff;
        setTitle("Admin Dashboard");

        initialCreateUserDialog();

        lbWelcomeTitle.setText("Admin staff - " + adminStaff.getFullName());

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"User ID", "Full Name", "Email", "Phone Number", "Role", "Active"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        tbInsuranceNetwork.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"Insurance ID", "Provider", "Coverage %", "Accepted"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        
        tbDoctorAssignment.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"Doctor ID", "Doctor", "Manager ID", "Medical Manager"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        loadUsers();
        loadInsuranceNetwork();
    }

    private void loadInsuranceNetwork() {
        DefaultTableModel model = (DefaultTableModel) tbInsuranceNetwork.getModel();

        model.setRowCount(0);

        ArrayList<InsuranceNetwork> insuranceNetworks = adminStaff.getInsuranceNetworks();

        for (InsuranceNetwork insurance : insuranceNetworks) {
            model.addRow(new Object[]{
                insurance.getInsuranceId(),
                insurance.getProviderName(),
                insurance.getCoverageRate(),
                insurance.isAccepted()
            });
        }
    }

    private void loadUsers() {
        DefaultTableModel model = (DefaultTableModel) tbUsers.getModel();

        model.setRowCount(0);

        ArrayList<User> users = adminStaff.getUsers();

        for (User user : users) {
            model.addRow(new Object[]{
                user.getUserId(),
                user.getFullName(),
                user.getEmail(),
                user.getPhoneNumber(),
                user.getRole(),
                user.isActive()
            });
        }
    }

    private void initialCreateUserDialog() {
        editingUserId = null;

        cbRole.removeAllItems();
        cbRole.addItem("ADMIN");
        cbRole.addItem("MEDICAL_MANAGER");
        cbRole.addItem("DOCTOR");
        cbRole.addItem("PATIENT");

        txtFullName.setText("");
        txtEmail.setText("");
        txtPhoneNumber.setText("");
        txtPassword.setText("");

        cbRole.setSelectedIndex(0);
        cbActive.setSelected(true);

        btnCreateUser.setText("Create");
        CreateUserDialog.setTitle("Create User");
    }

    private void initialInsuranceDialog() {
        editingInsuranceId = null;

        txtProvider.setText("");
        txtCoverage.setText("");
        cbAccepted.setSelected(true);

        btnAddInsuranceNetwork.setText("Add");
        CreateInsuranceNetworkDialog.setTitle("Add Insurance Network");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateUserDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        txtFullName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cbRole = new javax.swing.JComboBox<>();
        cbActive = new javax.swing.JCheckBox();
        btnCreateUser = new javax.swing.JButton();
        btnCancelCreateUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CreateInsuranceNetworkDialog = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        btnAddInsuranceNetwork = new javax.swing.JButton();
        btnCancelInsuranceNetwork = new javax.swing.JButton();
        txtProvider = new javax.swing.JTextField();
        txtCoverage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbAccepted = new javax.swing.JCheckBox();
        MainPanel = new javax.swing.JPanel();
        tabAdminDashboard = new javax.swing.JTabbedPane();
        UsersPanel = new javax.swing.JPanel();
        btnRefreshUsers = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        DoctorAssignmentPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDoctorAssignment = new javax.swing.JTable();
        InsuranceNetworkPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbInsuranceNetwork = new javax.swing.JTable();
        btnAddInsurance = new javax.swing.JButton();
        btnEditInsurance = new javax.swing.JButton();
        lbWelcomeTitle = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbActive.setText("active");

        btnCreateUser.setText("Create");
        btnCreateUser.addActionListener(this::btnCreateUserActionPerformed);

        btnCancelCreateUser.setText("Cancel");
        btnCancelCreateUser.addActionListener(this::btnCancelCreateUserActionPerformed);

        jLabel2.setText("Full Name");

        jLabel3.setText("Email");

        jLabel4.setText("Phone Number");

        jLabel5.setText("Password");

        jLabel6.setText("Role");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFullName)
                            .addComponent(txtEmail)
                            .addComponent(txtPhoneNumber)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCreateUser)
                                .addGap(39, 39, 39)
                                .addComponent(btnCancelCreateUser))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(cbActive)))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(cbActive)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateUser)
                    .addComponent(btnCancelCreateUser))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CreateUserDialogLayout = new javax.swing.GroupLayout(CreateUserDialog.getContentPane());
        CreateUserDialog.getContentPane().setLayout(CreateUserDialogLayout);
        CreateUserDialogLayout.setHorizontalGroup(
            CreateUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CreateUserDialogLayout.setVerticalGroup(
            CreateUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CreateInsuranceNetworkDialog.setPreferredSize(new java.awt.Dimension(472, 395));

        btnAddInsuranceNetwork.setText("Add");
        btnAddInsuranceNetwork.addActionListener(this::btnAddInsuranceNetworkActionPerformed);

        btnCancelInsuranceNetwork.setText("Cancel");
        btnCancelInsuranceNetwork.addActionListener(this::btnCancelInsuranceNetworkActionPerformed);

        jLabel7.setText("Provider:");

        jLabel8.setText("Coverage %:");

        cbAccepted.setText("Accepted");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddInsuranceNetwork)
                .addGap(112, 112, 112)
                .addComponent(btnCancelInsuranceNetwork)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAccepted)
                    .addComponent(txtCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addComponent(cbAccepted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelInsuranceNetwork)
                    .addComponent(btnAddInsuranceNetwork))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout CreateInsuranceNetworkDialogLayout = new javax.swing.GroupLayout(CreateInsuranceNetworkDialog.getContentPane());
        CreateInsuranceNetworkDialog.getContentPane().setLayout(CreateInsuranceNetworkDialogLayout);
        CreateInsuranceNetworkDialogLayout.setHorizontalGroup(
            CreateInsuranceNetworkDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CreateInsuranceNetworkDialogLayout.setVerticalGroup(
            CreateInsuranceNetworkDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnRefreshUsers.setText("Refresh");
        btnRefreshUsers.addActionListener(this::btnRefreshUsersActionPerformed);

        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(this::btnDeleteUserActionPerformed);

        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(this::btnAddUserActionPerformed);

        btnEditUser.setText("Edit User");
        btnEditUser.addActionListener(this::btnEditUserActionPerformed);

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsers.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbUsers);

        javax.swing.GroupLayout UsersPanelLayout = new javax.swing.GroupLayout(UsersPanel);
        UsersPanel.setLayout(UsersPanelLayout);
        UsersPanelLayout.setHorizontalGroup(
            UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsersPanelLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(btnAddUser)
                .addGap(18, 18, 18)
                .addComponent(btnEditUser)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteUser)
                .addGap(18, 18, 18)
                .addComponent(btnRefreshUsers)
                .addGap(224, 224, 224))
        );
        UsersPanelLayout.setVerticalGroup(
            UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser)
                    .addComponent(btnEditUser)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnRefreshUsers))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabAdminDashboard.addTab("Users", UsersPanel);

        tbDoctorAssignment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbDoctorAssignment);

        javax.swing.GroupLayout DoctorAssignmentPanelLayout = new javax.swing.GroupLayout(DoctorAssignmentPanel);
        DoctorAssignmentPanel.setLayout(DoctorAssignmentPanelLayout);
        DoctorAssignmentPanelLayout.setHorizontalGroup(
            DoctorAssignmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );
        DoctorAssignmentPanelLayout.setVerticalGroup(
            DoctorAssignmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorAssignmentPanelLayout.createSequentialGroup()
                .addGap(0, 344, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabAdminDashboard.addTab("Doctor Assignment", DoctorAssignmentPanel);

        tbInsuranceNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbInsuranceNetwork.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbInsuranceNetwork);

        btnAddInsurance.setText("Add Insurance");
        btnAddInsurance.addActionListener(this::btnAddInsuranceActionPerformed);

        btnEditInsurance.setText("Edit Insurance");
        btnEditInsurance.addActionListener(this::btnEditInsuranceActionPerformed);

        javax.swing.GroupLayout InsuranceNetworkPanelLayout = new javax.swing.GroupLayout(InsuranceNetworkPanel);
        InsuranceNetworkPanel.setLayout(InsuranceNetworkPanelLayout);
        InsuranceNetworkPanelLayout.setHorizontalGroup(
            InsuranceNetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(InsuranceNetworkPanelLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(btnAddInsurance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditInsurance)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        InsuranceNetworkPanelLayout.setVerticalGroup(
            InsuranceNetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsuranceNetworkPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(InsuranceNetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddInsurance)
                    .addComponent(btnEditInsurance))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabAdminDashboard.addTab("Insurance", InsuranceNetworkPanel);

        lbWelcomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbWelcomeTitle.setText("Admin staff - USER NAME");

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWelcomeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
            .addComponent(tabAdminDashboard, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWelcomeTitle)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabAdminDashboard))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to logout?",
                "Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        adminStaff = null;

        CreateUserDialog.dispose();
        CreateInsuranceNetworkDialog.dispose();

        dispose();

        loginchangelater loginPage = new loginchangelater();
        loginPage.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshUsersActionPerformed
        loadUsers();
    }//GEN-LAST:event_btnRefreshUsersActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        initialCreateUserDialog();

        CreateUserDialog.pack();
        CreateUserDialog.setLocationRelativeTo(this);
        CreateUserDialog.setVisible(true);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        String fullName = txtFullName.getText().trim();
        String email = txtEmail.getText().trim();
        String phoneNumber = txtPhoneNumber.getText().trim();
        String password = new String(txtPassword.getPassword());
        String role = cbRole.getSelectedItem().toString();
        boolean active = cbActive.isSelected();

        if (fullName.isEmpty() || email.isEmpty() || phoneNumber.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(CreateUserDialog, "Please fill in all fields.");
            return;
        }

        User user = null;

//        CREATE
        if (editingUserId == null) {
            switch (role) {
                case "ADMIN":
                    user = new AdminStaff(
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "MEDICAL_MANAGER":
                    user = new MedicalManager(
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "DOCTOR":
                    user = new Doctor(
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "PATIENT":
                    user = new Patient(
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;
            }

            if (user != null) {
                boolean success = adminStaff.createUser(user);
                if (success) {
                    JOptionPane.showMessageDialog(CreateUserDialog, "User created successfully.");
                    CreateUserDialog.dispose();

                    loadUsers();
                } else {
                    JOptionPane.showMessageDialog(CreateUserDialog, "Failed to create user.");
                }
            }
        } else {
//            EDIT
            switch (role) {
                case "ADMIN":
                    user = new AdminStaff(
                            editingUserId,
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "MEDICAL_MANAGER":
                    user = new MedicalManager(
                            editingUserId,
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "DOCTOR":
                    user = new Doctor(
                            editingUserId,
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;

                case "PATIENT":
                    user = new Patient(
                            editingUserId,
                            fullName,
                            email,
                            phoneNumber,
                            password,
                            active
                    );
                    break;
            }

            if (user != null) {
                boolean success = adminStaff.updateUser(user);

                if (success) {
                    JOptionPane.showMessageDialog(CreateUserDialog, "User updated successfully.");

                    CreateUserDialog.dispose();

                    editingUserId = null;

                    loadUsers();
                } else {
                    JOptionPane.showMessageDialog(CreateUserDialog, "Failed to update user.");
                }
            }
        }
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnCancelCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelCreateUserActionPerformed
        editingUserId = null;
        CreateUserDialog.dispose();
    }//GEN-LAST:event_btnCancelCreateUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        int selectedRow = tbUsers.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to delete.");
            return;
        }

        String userId = tbUsers.getValueAt(selectedRow, 0).toString();
        String fullName = tbUsers.getValueAt(selectedRow, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete "
                + fullName
                + " (" + userId + ")?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        boolean success = adminStaff.deleteUser(userId);

        if (success) {
            JOptionPane.showMessageDialog(this, "User deleted successfully.");
            loadUsers();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete user.", "Delete Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        int selectedRow = tbUsers.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to edit.");
            return;
        }

        String userId = tbUsers.getValueAt(selectedRow, 0).toString();

        User user = adminStaff.getUser(userId);

        if (user == null) {
            JOptionPane.showMessageDialog(this, "User could not be found.");
            return;
        }

//        Select user want to edit
        editingUserId = userId;

        txtFullName.setText(user.getFullName());
        txtEmail.setText(user.getEmail());
        txtPhoneNumber.setText(user.getPhoneNumber());
        txtPassword.setText(user.getPassword());
        cbRole.setSelectedItem(user.getRole().toString());
        cbActive.setSelected(user.isActive());

        btnCreateUser.setText("Save Changes");
        CreateUserDialog.setTitle("Edit User");

        CreateUserDialog.pack();
        CreateUserDialog.setLocationRelativeTo(this);
        CreateUserDialog.setVisible(true);
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnAddInsuranceNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInsuranceNetworkActionPerformed
        // TODO add your handling code here:
        String providerName = txtProvider.getText().trim();
        String coverageText = txtCoverage.getText().trim();
        boolean accepted = cbAccepted.isSelected();

        if (providerName.isEmpty() || coverageText.isEmpty()) {
            JOptionPane.showMessageDialog(
                    CreateInsuranceNetworkDialog,
                    "Please fill in all fields."
            );
            return;
        }

        double coverageRate;

        try {
            coverageRate = Double.parseDouble(coverageText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    CreateInsuranceNetworkDialog,
                    "Coverage must be a number."
            );
            return;
        }

        boolean success;

        // CREATE
        if (editingInsuranceId == null) {

            success = adminStaff.createInsuranceNetwork(
                    providerName,
                    coverageRate,
                    accepted
            );

            if (success) {
                JOptionPane.showMessageDialog(
                        CreateInsuranceNetworkDialog,
                        "Insurance network created successfully."
                );
            } else {
                JOptionPane.showMessageDialog(
                        CreateInsuranceNetworkDialog,
                        "Failed to create insurance network."
                );
                return;
            }

        } else {

            // EDIT
            success = adminStaff.updateInsuranceNetwork(
                    editingInsuranceId,
                    providerName,
                    coverageRate,
                    accepted
            );

            if (success) {
                JOptionPane.showMessageDialog(
                        CreateInsuranceNetworkDialog,
                        "Insurance network updated successfully."
                );
            } else {
                JOptionPane.showMessageDialog(
                        CreateInsuranceNetworkDialog,
                        "Failed to update insurance network."
                );
                return;
            }
        }

        CreateInsuranceNetworkDialog.dispose();

        editingInsuranceId = null;

        loadInsuranceNetwork();
    }//GEN-LAST:event_btnAddInsuranceNetworkActionPerformed

    private void btnCancelInsuranceNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelInsuranceNetworkActionPerformed
        // TODO add your handling code here:
        editingInsuranceId = null;
        CreateInsuranceNetworkDialog.dispose();
    }//GEN-LAST:event_btnCancelInsuranceNetworkActionPerformed

    private void btnAddInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInsuranceActionPerformed
        // TODO add your handling code here:
        initialInsuranceDialog();

        CreateInsuranceNetworkDialog.pack();
        CreateInsuranceNetworkDialog.setLocationRelativeTo(this);
        CreateInsuranceNetworkDialog.setVisible(true);
    }//GEN-LAST:event_btnAddInsuranceActionPerformed

    private void btnEditInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInsuranceActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbInsuranceNetwork.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select an insurance network to edit."
            );
            return;
        }

        editingInsuranceId = tbInsuranceNetwork.getValueAt(selectedRow, 0).toString();

        String providerName
                = tbInsuranceNetwork.getValueAt(selectedRow, 1).toString();

        String coverageRate
                = tbInsuranceNetwork.getValueAt(selectedRow, 2).toString();

        boolean accepted
                = Boolean.parseBoolean(
                        tbInsuranceNetwork
                                .getValueAt(selectedRow, 3)
                                .toString()
                );

        txtProvider.setText(providerName);
        txtCoverage.setText(coverageRate);
        cbAccepted.setSelected(accepted);

        btnAddInsuranceNetwork.setText("Save Changes");
        CreateInsuranceNetworkDialog.setTitle(
                "Edit Insurance Network"
        );

        CreateInsuranceNetworkDialog.pack();
        CreateInsuranceNetworkDialog.setLocationRelativeTo(this);
        CreateInsuranceNetworkDialog.setVisible(true);
    }//GEN-LAST:event_btnEditInsuranceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CreateInsuranceNetworkDialog;
    private javax.swing.JDialog CreateUserDialog;
    private javax.swing.JPanel DoctorAssignmentPanel;
    private javax.swing.JPanel InsuranceNetworkPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel UsersPanel;
    private javax.swing.JButton btnAddInsurance;
    private javax.swing.JButton btnAddInsuranceNetwork;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCancelCreateUser;
    private javax.swing.JButton btnCancelCreateUser1;
    private javax.swing.JButton btnCancelCreateUser2;
    private javax.swing.JButton btnCancelCreateUser3;
    private javax.swing.JButton btnCancelInsuranceNetwork;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnCreateUser1;
    private javax.swing.JButton btnCreateUser2;
    private javax.swing.JButton btnCreateUser3;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditInsurance;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefreshUsers;
    private javax.swing.JCheckBox cbAccepted;
    private javax.swing.JCheckBox cbActive;
    private javax.swing.JCheckBox cbActive1;
    private javax.swing.JCheckBox cbActive2;
    private javax.swing.JCheckBox cbActive3;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JComboBox<String> cbRole1;
    private javax.swing.JComboBox<String> cbRole2;
    private javax.swing.JComboBox<String> cbRole3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbWelcomeTitle;
    private javax.swing.JTabbedPane tabAdminDashboard;
    private javax.swing.JTable tbDoctorAssignment;
    private javax.swing.JTable tbInsuranceNetwork;
    private javax.swing.JTable tbUsers;
    private javax.swing.JTextField txtCoverage;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtEmail3;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtFullName1;
    private javax.swing.JTextField txtFullName2;
    private javax.swing.JTextField txtFullName3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JPasswordField txtPassword3;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoneNumber1;
    private javax.swing.JTextField txtPhoneNumber2;
    private javax.swing.JTextField txtPhoneNumber3;
    private javax.swing.JTextField txtProvider;
    // End of variables declaration//GEN-END:variables
}
